name: Build and Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        node: [ '12', '14', '16' ]

    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Setup node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node }}
      # - run: npm ci
      # - run: npm run test

      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Dependabot metadata
      #   if: ${{ github.actor == 'dependabot[bot]' }}
      #   id: metadata
      #   uses: dependabot/fetch-metadata@v1.1.1
      #   with:
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
